[package]
name = "actions_commit"
version = "0.1.0"
edition = "2021"

[lib]
name = "actions_commit"
path = "src/lib.rs"

[[bin]]
name = "action"
path = "src/bin.rs"

[dependencies]
actions-toolkit = { git = "https://github.com/dev-bio/actions-toolkit.git", rev = "06eb843baf76eea5dff6ae3e4d4d11e35bf958e3" }
glob = { version = "0.3.1" }
anyhow = "1.0.72"
